---
language: node_js
node_js:
  - "6"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: false

cache:
  directories:
    - node_modules

env:
  # we recommend testing LTS's and latest stable release (bonus points to beta/canary)
  - CXX=g++-4.8 EMBER_TRY_SCENARIO=ember-1.13
  - CXX=g++-4.8 EMBER_TRY_SCENARIO=ember-lts-2.4
  - CXX=g++-4.8 EMBER_TRY_SCENARIO=ember-release
  - CXX=g++-4.8 EMBER_TRY_SCENARIO=ember-beta
  - CXX=g++-4.8 EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g yarn
  - yarn global add bower
  - bower --version
  - yarn add phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - yarn install --pure-lockfile
  - bower install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
